default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test

production:
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL') %>
