default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test

production:
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL') %>
